### ISSUE TITLE
Unable to retrieve AMIs to clean

### ISSUE THREAD

**Issue by rlochen** [bonclay7/aws-amicleaner#106]
Retrieving AMIs to clean ... 
Traceback (most recent call last): 
  File "/usr/local/bin/amicleaner", line 11, in <module> 
    sys.exit(main()) 
  File "/usr/local/lib/python2.7/site-packages/amicleaner/cli.py", line 195, in main 
    app.run_cli() 
  File "/usr/local/lib/python2.7/site-packages/amicleaner/cli.py", line 165, in run_cli 
    candidates = self.prepare_candidates() 
  File "/usr/local/lib/python2.7/site-packages/amicleaner/cli.py", line 66, in prepare_candidates 
    candidates_amis = candidates_amis or self.fetch_candidates() 
  File "/usr/local/lib/python2.7/site-packages/amicleaner/cli.py", line 53, in fetch_candidates 
    excluded_amis += f.fetch_zeroed_asg() 
  File "/usr/local/lib/python2.7/site-packages/amicleaner/fetch.py", line 71, in fetch_zeroed_asg 
    LaunchConfigurationNames=zeroed_lcs 
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 320, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 596, in _make_api_call 
    api_params, operation_model, context=request_context) 
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 632, in _convert_to_request_dict 
    api_params, operation_model) 
  File "/usr/local/lib/python2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request 
    raise ParamValidationError(report=report.generate_report()) 
botocore.exceptions.ParamValidationError: Parameter validation failed: 
Invalid length for parameter LaunchConfigurationNames[0], value: 0, valid range: 1-inf 
[Container] 2019/12/20 08:15:07 Command did not exit successfully amicleaner -f --mapping-key name --mapping-values ${AMI_TAG_NAME} --keep-previous ${AMI_RETENTION} exit status 1 
[Container] 2019/12/20 08:15:07 Phase complete: POST_BUILD State: FAILED 
[Container] 2019/12/20 08:15:07 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: amicleaner -f --mapping-key name --mapping-values ${AMI_TAG_NAME} --keep-previous ${AMI_RETENTION}. Reason: exit status 1

**Comment by Lusitaniae** [comment]
try python3?
