### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by brauliobo** [bonclay7/aws-amicleaner#55]
```
~/P/o/scripts ❯❯❯ amicleaner --full-report                                                                                                                                            master
Traceback (most recent call last):
  File "/usr/bin/amicleaner", line 11, in <module>
    load_entry_point('aws-amicleaner==0.1.2', 'console_scripts', 'amicleaner')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/amicleaner/cli.py", line 69
    print TERM.bold("\nCleaning from {} AMI id(s) ...".format(
             ^
SyntaxError: invalid syntax
```

**Comment by brauliobo** [comment]
shit, python 3 is being used, will (try) to switch to python 2
