### ISSUE TITLE
Can't run amicleaner -- botocore version conflict

### ISSUE THREAD

**Issue by dhait** [bonclay7/aws-amicleaner#76]
Running on Mac High Sierra, python 2.7.10.

After installing with pip (successfully) I attempt to run amicleaner --help.  I get the following:

Traceback (most recent call last):
  File "/usr/local/bin/amicleaner", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.8.49 (/usr/local/lib/python2.7/site-packages), Requirement.parse('botocore==1.7.41'), set(['awscli']))

**Comment by dhait** [comment]
Never mind, it just needed an awscli upgrade.  Working fine now.

**Comment by bonclay7** [comment]
Nice !

**Comment by jmilliron** [comment]
Thanks for coming back and posting the solution @dhait
