### ISSUE TITLE
No module named builtins

### ISSUE THREAD

**Issue by cloudlady911** [bonclay7/aws-amicleaner#91]
I am getting the following error:

```
[ec2-user@operator ~]$ sudo amicleaner --full-report
Traceback (most recent call last):
  File "/usr/local/bin/amicleaner", line 11, in <module>
    load_entry_point('aws-amicleaner==0.2.2', 'console_scripts', 'amicleaner')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/amicleaner/cli.py", line 6, in <module>
    from builtins import input
ImportError: No module named builtins
```

Python 2.7
Latest AWSCLI

**Comment by finferflu** [comment]
I've fixed this by running 

```pip install future```

I think this needs to be added as a dependency.

**Comment by cloudlady911** [comment]
Thanks I will give this a try

**Comment by ccggeo** [comment]
This is still a problem. Is this project being actively maintained anymore?
